import { useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bar, Doughnut } from "react-chartjs-2";
import { ArcElement, BarElement, CategoryScale, Chart as ChartJS, Legend, LinearScale, Tooltip } from "chart.js";
import { Activity, BarChart3, Check, ClipboardList, FileCheck2, Megaphone, RefreshCcw, Search, X } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Modal } from "@/components/ui/Modal";
import { Input } from "@/components/ui/Input";
import { Skeleton } from "@/components/ui/Skeleton";
import { SectionCard, StatCard } from "@/features/dashboards/shared/widgets";
import { announcementsApi } from "@/features/announcements/services/announcementsApi";
import { authApi } from "@/features/auth/services/authApi";
import { useAuth } from "@/features/auth/context/AuthContext";
import { eventsApi, registrationsApi } from "@/features/events/services/eventsApi";
import { usersApi } from "@/features/users/services/usersApi";
import { adminApi } from "@/features/admin/services/adminApi";
import { useToast } from "@/providers/ToastProvider";

ChartJS.register(BarElement, CategoryScale, LinearScale, ArcElement, Tooltip, Legend);
const toneFor = (status: string): "neutral" | "success" | "warning" | "danger" | "info" => ({ published: "success", approved: "success", pending: "warning", pending_approval: "warning", rejected: "danger", cancelled: "danger", waitlisted: "info" }[status] as never) || "neutral";

export function ApprovalsPage() {
  const qc = useQueryClient(); const { toast } = useToast(); const [confirm, setConfirm] = useState<{ type: "announcement" | "event"; id: string; decision: "approved" | "rejected" | "returned"; label: string } | null>(null);
  const announcements = useQuery({ queryKey: ["admin", "pending-announcements"], queryFn: adminApi.pendingAnnouncements });
  const events = useQuery({ queryKey: ["admin", "pending-events"], queryFn: adminApi.pendingEvents });
  const action = useMutation({ mutationFn: async ({ type, id, decision }: { type: "announcement" | "event"; id: string; decision: "approved" | "rejected" | "returned" }) => type === "announcement" ? announcementsApi.approve(id, decision) : eventsApi.approve(id, decision), onSuccess: () => { toast("Approval updated.", "success"); qc.invalidateQueries({ queryKey: ["admin"] }); }, onError: () => toast("Approval action failed.", "error") });
  const requestAction = (type: "announcement" | "event", id: string, decision: "approved" | "rejected" | "returned", label: string) => setConfirm({ type, id, decision, label });
  const rows = [...(announcements.data ?? []).map((item) => ({ ...item, type: "Announcement" as const })), ...(events.data ?? []).map((item) => ({ ...item, type: "Event" as const }))];
  return <AdminPage title="Approvals" subtitle="Review pending announcements and event proposals."><Card className="overflow-hidden border-slate-200 p-0 shadow-sm"><div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Submission</th><th>Type</th><th>Submitted</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((item) => { const type = item.type === "Announcement" ? "announcement" : "event"; return <tr key={item.id}><td><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-100 p-2 text-blue-700">{item.type === "Announcement" ? <Megaphone size={18} /> : <FileCheck2 size={18} />}</span><div><p className="font-bold text-[#102858]">{item.title}</p><p className="text-xs text-slate-500">{item.type === "Announcement" ? item.summary ?? "Announcement submission" : item.description ?? "Event proposal"}</p></div></div></td><td><Badge tone="info">{item.type}</Badge></td><td>{new Date(item.created_at).toLocaleString()}</td><td><Badge tone={toneFor(item.status)}>{item.status.replaceAll("_", " ")}</Badge></td><td><div className="flex flex-wrap gap-2"><Button size="sm" disabled={action.isPending} onClick={() => requestAction(type, item.id, "approved", "Approve this submission?")}><Check size={14} className="mr-1" />Approve</Button><Button size="sm" variant="secondary" disabled={action.isPending} onClick={() => requestAction(type, item.id, "returned", "Return this submission for revision?")}>Revise</Button><Button size="sm" variant="danger" disabled={action.isPending} onClick={() => requestAction(type, item.id, "rejected", "Reject this submission?")}><X size={14} className="mr-1" />Reject</Button></div></td></tr>; })}</tbody></table></div>{!rows.length && <EmptyState label="No pending approvals." />}</Card><Modal open={Boolean(confirm)} title="Confirm approval action" onClose={() => setConfirm(null)} footer={<><Button variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button><Button variant={confirm?.decision === "rejected" ? "danger" : "primary"} disabled={action.isPending} onClick={() => { if (confirm) action.mutate(confirm, { onSettled: () => setConfirm(null) }); }}>{action.isPending ? "Saving..." : "Confirm"}</Button></>}><p className="text-sm text-slate-600">{confirm?.label}</p></Modal></AdminPage>;
}

export function ReportsPage() {
  const report = useQuery({ queryKey: ["admin", "reports"], queryFn: adminApi.reportDashboard });
  if (report.isLoading) return <AdminPage title="Reports" subtitle="Analytics and insights about school activity."><Skeleton variant="rectangular" height={260} /></AdminPage>;
  if (report.isError) return <AdminPage title="Reports" subtitle="Analytics and insights about school activity."><Card className="p-8 text-center text-sm text-red-600">Could not load reports. <button className="font-semibold underline" onClick={() => report.refetch()}>Try again</button></Card></AdminPage>;
  const data = report.data; const statuses = data?.registrations.by_status ?? {}; const attendanceTotal = Object.values(data?.attendance ?? {}).reduce((a, b) => a + b, 0); const attendanceRate = attendanceTotal ? Math.round(((data?.attendance?.present ?? 0) / attendanceTotal) * 100) : 0;
  return <AdminPage title="Reports" subtitle="Analytics and insights about school events and participation."><div className="grid gap-4 md:grid-cols-3"><StatCard label="Total Events" value={data?.total_events ?? 0} icon={BarChart3} /><StatCard label="Upcoming Events" value={data?.upcoming_events ?? 0} icon={Activity} tone="green" /><StatCard label="Total Registrations" value={data?.registrations.total ?? 0} icon={ClipboardList} tone="violet" /><StatCard label="Attendance Rate" value={attendanceTotal ? `${attendanceRate}%` : "Unavailable"} icon={ClipboardList} tone="blue" /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="Registration status"><div className="mx-auto max-w-sm"><Doughnut data={{ labels: Object.keys(statuses), datasets: [{ data: Object.values(statuses), backgroundColor: ["#2563eb", "#10b981", "#f59e0b", "#8b5cf6", "#ef4444"] }] }} /></div></SectionCard><SectionCard title="Popular categories"><Bar data={{ labels: (data?.popular_categories ?? []).map((x) => x.category), datasets: [{ label: "Registrations", data: (data?.popular_categories ?? []).map((x) => x.registrations), backgroundColor: "#2563eb", borderRadius: 8 }] }} options={{ responsive: true, plugins: { legend: { display: false } } }} /></SectionCard></div><SectionCard title="Attendance by department" className="mt-5"><div className="space-y-3">{(data?.department_attendance ?? []).map((row) => <div key={row.department} className="flex items-center gap-3 text-sm"><span className="w-40 truncate font-medium">{row.department}</span><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${row.percentage}%` }} /></div><span className="w-16 text-right font-bold">{row.percentage}%</span></div>)}</div>{!data?.department_attendance?.length && <EmptyState label="No department attendance data available." />}</SectionCard></AdminPage>;
}

export function ActivityLogsPage() {
  const [page, setPage] = useState(1); const [action, setAction] = useState(""); const logs = useQuery({ queryKey: ["admin", "audit", page, action], queryFn: () => adminApi.auditLogs(page, action || undefined) });
  return <AdminPage title="Activity Logs" subtitle="Track important administrative actions and system activity."><Card className="border-slate-200 p-0 shadow-sm"><div className="flex flex-wrap gap-3 border-b border-slate-100 p-4"><div className="relative min-w-[240px] flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400" /><Input className="pl-9" placeholder="Filter by action..." value={action} onChange={(event) => { setAction(event.target.value); setPage(1); }} /></div><Button variant="secondary" onClick={() => logs.refetch()}><RefreshCcw size={16} className="mr-2" />Refresh</Button></div>{logs.isError && <p className="p-5 text-sm text-red-600">Could not load activity logs. <button className="font-semibold underline" onClick={() => logs.refetch()}>Try again</button></p>}<div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Timestamp</th><th>Action</th><th>Module</th><th>Actor</th><th>IP address</th></tr></thead><tbody>{(logs.data?.data ?? []).map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td className="font-semibold text-[#102858]">{item.action}</td><td><Badge tone="info">{item.entity_type}</Badge></td><td>{item.actor_name ?? "System"}</td><td>{item.ip_address ?? "—"}</td></tr>)}</tbody></table></div>{!logs.isLoading && !logs.isError && !logs.data?.data.length && <EmptyState label="No activity logs found." />}<Pager page={page} totalPages={logs.data?.meta?.total_pages ?? 0} onChange={setPage} /></Card></AdminPage>;
}

export function AdminRegistrationsPage() {
  const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [confirm, setConfirm] = useState<{ id: string; decision?: "approved" | "rejected"; action?: "promote" | "remove"; label: string } | null>(null); const qc = useQueryClient(); const { toast } = useToast(); const registrations = useQuery({ queryKey: ["admin", "registrations", page, status], queryFn: () => adminApi.allRegistrations(page, status || undefined) });
  const decide = useMutation({ mutationFn: ({ id, decision }: { id: string; decision: "approved" | "rejected" }) => registrationsApi.decide(id, decision), onSuccess: () => { toast("Registration updated.", "success"); qc.invalidateQueries({ queryKey: ["admin", "registrations"] }); }, onError: () => toast("Registration action failed.", "error") });
  const exportCsv = () => { const rows = registrations.data?.data ?? []; const csv = ["registration_id,event_id,status,created_at", ...rows.map((item) => `${item.id},${item.event_id},${item.status},${item.created_at}`)].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "registrations.csv"; link.click(); URL.revokeObjectURL(link.href); };
  const manage = useMutation({ mutationFn: async ({ id, action }: { id: string; action: "promote" | "remove" }) => action === "promote" ? registrationsApi.promote(id) : registrationsApi.remove(id), onSuccess: () => { toast("Registration updated.", "success"); qc.invalidateQueries({ queryKey: ["admin", "registrations"] }); }, onError: () => toast("Registration action failed.", "error") });
  const confirmAction = () => { if (!confirm) return; if (confirm.decision) decide.mutate({ id: confirm.id, decision: confirm.decision }, { onSettled: () => setConfirm(null) }); else if (confirm.action) manage.mutate({ id: confirm.id, action: confirm.action }, { onSettled: () => setConfirm(null) }); };
  return <AdminPage title="Registrations" subtitle="Monitor and manage student registrations for school events."><Card className="border-slate-200 p-0 shadow-sm"><div className="flex flex-wrap gap-3 border-b border-slate-100 p-4"><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{["pending", "approved", "waitlisted", "cancelled", "rejected"].map((x) => <option key={x}>{x}</option>)}</select><Button variant="secondary" onClick={exportCsv}>Export CSV</Button></div><div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Participant</th><th>Event</th><th>Status</th><th>Registered</th><th>Actions</th></tr></thead><tbody>{(registrations.data?.data ?? []).map((item) => <tr key={item.id}><td className="font-medium">{item.participant_name ?? "Participant"}</td><td>{item.event_title ?? "Event"}</td><td><Badge tone={toneFor(item.status)}>{item.status}</Badge></td><td>{new Date(item.created_at).toLocaleString()}</td><td><div className="flex flex-wrap gap-2">{item.status === "pending" && <><Button size="sm" disabled={decide.isPending} onClick={() => setConfirm({ id: item.id, decision: "approved", label: "Approve this registration?" })}>Approve</Button><Button size="sm" variant="danger" disabled={decide.isPending} onClick={() => setConfirm({ id: item.id, decision: "rejected", label: "Reject this registration?" })}>Reject</Button></>}{item.status === "waitlisted" && <Button size="sm" variant="secondary" disabled={manage.isPending} onClick={() => setConfirm({ id: item.id, action: "promote", label: "Move this participant into the event capacity?" })}>Promote</Button>}<Button size="sm" variant="danger" disabled={manage.isPending} onClick={() => setConfirm({ id: item.id, action: "remove", label: "Remove this registration?" })}>Remove</Button></div></td></tr>)}</tbody></table></div>{!registrations.data?.data.length && <EmptyState label="No registrations found." />}<Pager page={page} totalPages={registrations.data?.meta?.total_pages ?? 0} onChange={setPage} /></Card><Modal open={Boolean(confirm)} title="Confirm registration action" onClose={() => setConfirm(null)} footer={<><Button variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button><Button variant={confirm?.decision === "rejected" || confirm?.action === "remove" ? "danger" : "primary"} onClick={confirmAction}>Confirm</Button></>}><p className="text-sm text-slate-600">{confirm?.label}</p></Modal></AdminPage>;
}

export function SettingsPage() {
  const { user } = useAuth(); const { toast } = useToast();
  const [profile, setProfile] = useState({ first_name: user?.first_name ?? "", last_name: user?.last_name ?? "", phone: user?.phone ?? "" });
  const [passwords, setPasswords] = useState({ current: "", next: "" });
  const profileMut = useMutation({ mutationFn: () => usersApi.updateMyProfile({ first_name: profile.first_name || null, last_name: profile.last_name || null, phone: profile.phone || null }), onSuccess: () => toast("Profile updated.", "success"), onError: () => toast("Profile could not be updated.", "error") });
  const passwordMut = useMutation({ mutationFn: () => authApi.changePassword(passwords.current, passwords.next), onSuccess: () => { toast("Password changed.", "success"); setPasswords({ current: "", next: "" }); }, onError: () => toast("Password could not be changed.", "error") });
  return <AdminPage title="Settings" subtitle="Administrator workspace preferences."><div className="grid gap-5 xl:grid-cols-2"><Card className="border-slate-200 shadow-sm"><h2 className="mb-4 font-bold text-[#102858]">Profile</h2><div className="space-y-3"><Input placeholder="First name" value={profile.first_name} onChange={(event) => setProfile({ ...profile, first_name: event.target.value })} /><Input placeholder="Last name" value={profile.last_name} onChange={(event) => setProfile({ ...profile, last_name: event.target.value })} /><Input placeholder="Phone" value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /><Button isLoading={profileMut.isPending} onClick={() => profileMut.mutate()}>Save profile</Button></div></Card><Card className="border-slate-200 shadow-sm"><h2 className="mb-4 font-bold text-[#102858]">Password</h2><div className="space-y-3"><Input type="password" placeholder="Current password" value={passwords.current} onChange={(event) => setPasswords({ ...passwords, current: event.target.value })} /><Input type="password" placeholder="New password" value={passwords.next} onChange={(event) => setPasswords({ ...passwords, next: event.target.value })} /><Button isLoading={passwordMut.isPending} disabled={!passwords.current || passwords.next.length < 8} onClick={() => passwordMut.mutate()}>Change password</Button></div></Card></div><Card className="mt-5 border-slate-200 shadow-sm"><h2 className="mb-2 font-bold text-[#102858]">School-wide settings</h2><p className="text-sm text-slate-600">Server-wide configuration controls are not exposed by the backend yet, so they are intentionally unavailable here.</p></Card></AdminPage>;
}
function AdminPage({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Administrator</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#102858]">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p></div>{children}</div>; }
function EmptyState({ label }: { label: string }) { return <div className="p-10 text-center text-sm text-slate-500">{label}</div>; }
function Pager({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) { return totalPages > 1 ? <div className="flex items-center justify-end gap-2 border-t border-slate-100 p-4"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => onChange(page - 1)}>Previous</Button><span className="text-xs text-slate-500">Page {page} of {totalPages}</span><Button size="sm" variant="secondary" disabled={page >= totalPages} onClick={() => onChange(page + 1)}>Next</Button></div> : null; }
