"""announcements module

Revision ID: 296019ba968e
Revises: 7ac13770eeb4
Create Date: 2026-07-18 19:54:44.356078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296019ba968e'
down_revision = '7ac13770eeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('normal','important','urgent')", name='ck_announcements_priority'),
    sa.CheckConstraint("status IN ('draft','pending_approval','published','archived')", name='ck_announcements_status'),
    sa.CheckConstraint('expires_at IS NULL OR published_at IS NULL OR expires_at >= published_at', name='ck_announcements_expiry'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['announcement_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_status'), ['status'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_uploaded_files_size'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('announcement_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_approvals_announcement_id'), ['announcement_id'], unique=False)

    op.create_table('announcement_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'file_id', name='uq_announcement_attachment')
    )
    with op.batch_alter_table('announcement_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_attachments_announcement_id'), ['announcement_id'], unique=False)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('announcement_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_attachments_announcement_id'))

    op.drop_table('announcement_attachments')
    with op.batch_alter_table('announcement_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_approvals_announcement_id'))

    op.drop_table('announcement_approvals')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_uploader_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_status'))
        batch_op.drop_index(batch_op.f('ix_announcements_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_announcements_category_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_author_id'))

    op.drop_table('announcements')
    op.drop_table('announcement_categories')
    # ### end Alembic commands ###
